# Generated by Django 4.1 on 2022-08-31 16:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Consigne',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('remarque', models.TextField(max_length=70)),
                ('date_consigne', models.DateTimeField()),
            ],
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('adresse', models.TextField(max_length=80)),
                ('code_postal', models.BigIntegerField()),
                ('prefecture_province', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Division',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Nature',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=30)),
                ('division', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courriers.division')),
            ],
        ),
        migrations.CreateModel(
            name='Type_contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Utilisateur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('identifiant', models.CharField(default='', max_length=10, unique=True)),
                ('nom', models.CharField(max_length=20)),
                ('prenom', models.CharField(max_length=20)),
                ('email', models.EmailField(default='', max_length=254)),
                ('telephone', models.BigIntegerField(max_length=14)),
                ('division', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.division')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courriers.role')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.service')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Courrierdepart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField(max_length=10, unique=True)),
                ('date_courrier', models.DateField()),
                ('adresse', models.TextField(max_length=50)),
                ('objet', models.TextField(max_length=60)),
                ('destination', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courriers.contact')),
                ('type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courriers.nature')),
            ],
        ),
        migrations.CreateModel(
            name='Courrier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priorite', models.CharField(choices=[('', ''), ('normal', 'Normal'), ('urgent', 'Urgent'), ('très urgent', 'Très urgent')], default='', max_length=30)),
                ('autre_consigne', models.CharField(blank=True, max_length=50)),
                ('date_courrier', models.DateField()),
                ('date_arrivee', models.DateField()),
                ('numero_ordre', models.BigIntegerField()),
                ('objet', models.TextField(max_length=70)),
                ('reference', models.CharField(max_length=10)),
                ('categorie', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.categorie')),
                ('consigne', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.consigne')),
                ('nature', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='courriers.nature')),
            ],
        ),
        migrations.AddField(
            model_name='contact',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courriers.type_contact'),
        ),
        migrations.CreateModel(
            name='Affectation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_limite_de_traitement', models.DateField()),
                ('courrier', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courriers.courrier')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='courriers.service')),
            ],
        ),
    ]
